name: Build and Push Docker Image

on:
  push:
    branches:
      - main   # Trigger this workflow on pushes to the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}" | docker login -u "${{ secrets.DOCKER_HUB_USERNAME }}" --password-stdin

    - name: Build and tag Docker image
      run: docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/onehint:${{ github.sha }} .

    - name: Tag Docker image as latest
      run: docker tag ${{ secrets.DOCKER_HUB_USERNAME }}/onehint:${{ github.sha }} ${{ secrets.DOCKER_HUB_USERNAME }}/onehint:latest

    - name: Push Docker image to Docker Hub
      run: docker push ${{ secrets.DOCKER_HUB_USERNAME }}/onehint:${{ github.sha }}

    - name: Push Docker image with latest tag
      run: docker push ${{ secrets.DOCKER_HUB_USERNAME }}/onehint:latest

    - name: Log out from Docker Hub
      run: docker logout
